# Home Assistant Test File
automation:
  - alias: "Test Automation"
    trigger:
      platform: state
      entity_id: sensor.temperature
    action:
      service: light.turn_on
      target:
        entity_id: light.living_room
