name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing tags
      id-token: write  # For NPM provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Check if version already published
        id: check
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          
          if npm view homeassistant-lsp@$PACKAGE_VERSION version 2>/dev/null; then
            echo "Version $PACKAGE_VERSION already published, skipping..."
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $PACKAGE_VERSION not published yet, proceeding..."
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to NPM
        if: steps.check.outputs.should_publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        if: steps.check.outputs.should_publish == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ steps.check.outputs.version }}" -m "Release v${{ steps.check.outputs.version }}"
          git push origin "v${{ steps.check.outputs.version }}"

      - name: Create GitHub Release
        if: steps.check.outputs.should_publish == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check.outputs.version }}
          release_name: v${{ steps.check.outputs.version }}
          body: |
            ## Changes in v${{ steps.check.outputs.version }}
            
            Published to NPM: https://www.npmjs.com/package/homeassistant-lsp/v/${{ steps.check.outputs.version }}
            
            ### Installation
            ```bash
            npm install -g homeassistant-lsp@${{ steps.check.outputs.version }}
            ```
          draft: false
          prerelease: false
